// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFAQ1iAmJ8fqLYsn8vS7MK4_5pU7vt1pA',
    appId: '1:808310563436:web:92a66fba2a2fdc34622e49',
    messagingSenderId: '808310563436',
    projectId: 'fir-seminario',
    authDomain: 'fir-seminario.firebaseapp.com',
    storageBucket: 'fir-seminario.firebasestorage.app',
    measurementId: 'G-H2C6M10322',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9d1QD90T5_SBSt7z2mcIlszEUsjvOqNI',
    appId: '1:808310563436:android:ac04d95aa85a7632622e49',
    messagingSenderId: '808310563436',
    projectId: 'fir-seminario',
    storageBucket: 'fir-seminario.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxAFPIpHuPZ74A9WIOwSHs2louWVkCLpQ',
    appId: '1:808310563436:ios:b8c254ac5cc7b11a622e49',
    messagingSenderId: '808310563436',
    projectId: 'fir-seminario',
    storageBucket: 'fir-seminario.firebasestorage.app',
    iosClientId: '808310563436-3hnu7k00mim27eb5ko6k3dh06mpdu943.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseseminario',
  );
}
